services:
  - type: web
    name: events-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn app.main:api -k uvicorn.workers.UvicornWorker
      -b 0.0.0.0:$PORT --workers 2 --timeout 60
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: events-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REFRESH_SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: TIMEZONE
        value: America/Sao_Paulo

databases:
  - name: events-db
    plan: free
    databaseName: events
    user: events_user
